### ISSUE TITLE
要不要考虑换个开源证书?

### ISSUE THREAD

**Issue by shuiRong** [vincenth520/pinche_xcx#1]
这种需求不算小众.代码很可能被某些人拿去,投放市场.(如果你不在乎的话,忽视这个issue)
(换个合适的证书,不会影响你开源的目的)

**Comment by vincenth520** [comment]
换成什么，并不是很懂这个

**Comment by vincenth520** [comment]
@shuiRong 换成什么，并不是很懂这个

**Comment by vincenth520** [comment]
@shuiRong  换成apache了，应该可以了，谢谢了,开源的本意是给新手学习

**Comment by shuiRong** [comment]
无论换成什么开源证书都不会影响到社区新手的学习....
[如何选择开源许可证？](http://www.ruanyifeng.com/blog/2011/05/how_to_choose_free_software_licenses.html)
