### ISSUE TITLE
关于路径配置问题

### ISSUE THREAD

**Issue by cbcbaochen** [vincenth520/pinche_xcx#11]
var rootDocment = 'https://sfc188.club/www/188/Apps/Api/';
报错VM2373 appservice:1083 POST https://sfc188.club/www/188/Apps/Api/user/vaild_sk 404 (Not Found)
         https://sfc188.club/www/188/Apps/Api/info/lists 404 (Not Found)
请问该如何配置？谢谢指教！

**Comment by vincenth520** [comment]
伪静态
