### ISSUE TITLE
前端在开发者工具和手机测试中获取不到头像

### ISSUE THREAD

**Issue by lebals** [vincenth520/pinche_xcx#5]
前端在开发者工具和手机测试中获取不到头像还报错，搞不明白了
http://cdn.29ym.com/o_1bqu20pcrariodg1p1l901vn5a.png
http://cdn.29ym.com/o_1bqu22gvldfrmi3uti1utcofja.png

**Comment by vincenth520** [comment]
@lebals 请检查你的appid是否与utils.js中的AppConf：appid是否一致，不一致无法获取openid从而登录失败

**Comment by lebals** [comment]
后端和前端是一致的，就是老提示登录已过期
http://cdn.29ym.com/o_1bqu55bg01u4nrrn13l614t6en0a.png

**Comment by vincenth520** [comment]
@lebals 最新代码是不需要部署后端的，意思就是不需要修改前端的api地址，只需要修改appid这些即可

**Comment by lebals** [comment]
哦这样，捣鼓了一上午 以为可以和后端一起用来。谢谢你了

**Comment by JAgreed-hand** [comment]
@vincenth520 你好这个出现了登陆失败我看了appconf 没有出错，是什么原因呢？？？
