### ISSUE TITLE
拼车小程序付费版pinche_xcx_vip 和 同城拼车微信小程序pinche_xcx有什么区别？

### ISSUE THREAD

**Issue by forconz** [vincenth520/pinche_xcx#9]
付费版是拼车客人付费吗？

拼车小程序付费版pinche_xcx_vip 能不能像同城拼车微信小程序pinche_xcx录制一下视频？

**Comment by vincenth520** [comment]
是需要付费使用的，需要授权

**Comment by dongeast** [comment]
那拼车小程序付费版pinche_xcx_vip的源代码你发布到github了，这个授权说明你没有给啊。
就是授权了，受限制的功能能使用了，还是能商用了，是不是给个说明？

**Comment by dongeast** [comment]
拼车小程序付费版pinche_xcx_vip 和 同城拼车微信小程序pinche_xcx
在功能上，性能上，有什么区别吗？能不能做一个版本比较？
你让用户花钱，也需要告诉用户为什么要花这个钱啊。

**Comment by vincenth520** [comment]
付费版安装需要授权码，没有授权码你下载也运行不了

**Comment by vincenth520** [comment]
付费版有后台，后期会更新

**Comment by dongeast** [comment]
付费版本，你能出一个视频吗？就是跟免费版有什么区别？我这边是愿意付费的。

**Comment by dongeast** [comment]
标准版(￥399)：指导小程序全部配置至上线，获得后续代码的升级版本，加入会员群获得专业指导支持
专业版(￥699)：帮助配置小程序直至上线，获得后续代码的升级版本，加入会员群获得专业指导支持
同城拼车后续计划

这2种付费，没有看明白具体的区别，建议你拉个表格，对比的看比较合适
项目            标准版           专业版
价格            ￥399             ￥699
技术支持    有                    有 
安装配置     无                   有
微信支付     无                   有

类似这样的对比表格，我们一看就明白了

**Comment by vincenth520** [comment]
正在写

**Comment by dongeast** [comment]
免费版本除重大bug不再更新，付费版本将持续完善前端版本，并后续开发后台管理平台

还有免费版本跟付费版本的区别，也建议一起罗列出来。
这样好处是，用户知道自己为什么花钱了。

付费版本，我建议开通一下微信支付，我这边可以提供商户信息，支付appid等信息。

**Comment by dongeast** [comment]
车找客，客找车，表单实际上是有区别的，建议区分下。

还有拼车的反馈需要加一下，拼车有没有半途甩客，像滴滴那样，用车后评价。当然司机也可以对拼客做评价。

**Comment by vincenth520** [comment]
写好了，https://github.com/vincenth520/pinche_xcx/blob/master/donate.md

**Comment by dongeast** [comment]
小程序端的功能区别，免费版和付费版没有罗列区别啊
你现在2个版本，功能是一样的吗？

**Comment by vincenth520** [comment]
前端基本一样，后端接口重构了，添加了后台管理，所以说看前端确实变化不大

**Comment by dongeast** [comment]
理解了，等产品能商用了，我来付费。

**Comment by vincenth520** [comment]
已经完成了现在
